services:
  mongo-test:
    container_name: mongo-test
    image: mongo
    restart: always
    ports:
      - 27017:27017

  weather-integration:
    build:
      context: ./packages/api
      dockerfile: apps/weather/Dockerfile.test
    command: sh -c "cd apps/weather && yarn test:integration"

  subscription-integration:
    build:
      context: ./packages/api
      dockerfile: apps/subscription/Dockerfile.test
    depends_on:
      - mongo-test
    command: sh -c "yarn migrate && cd apps/subscription && yarn test:integration"

  e2e-test:
    build:
      context: ./packages
      dockerfile: Dockerfile.playwright
    depends_on:
      - mongo-test
    command: sh -c "yarn migrate:test && yarn test:e2e"
