name: CI pipeline

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  eslinter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: yarn
          cache-dependency-path: packages/api/yarn.lock

      - name: Install dependencies in packages/api
        run: |
          cd packages/api
          yarn install

      - name: Run eslint
        run: |
          cd packages/api
          yarn lint

      - name: Run tests
        run: |
          cd packages/api
          yarn test:ci
