name: Linter CI pipeline

permissions:
  contents: read

on: [push]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node

      - name: Install dependencies in packages/api
        run: yarn install
        working-directory: packages/api

      - name: Run eslint
        run: yarn lint
        working-directory: packages/api
